version: 0.0
os: linux 
files:
  - source: 
    destination: /home/ec2-user/app
permissions:
  - object: /home/ec2-user/app
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStop:
    - location: aws/deployment/application_stop/stop_puma.sh
      timeout: 20
      runas: ec2-user
  BeforeInstall:
    - location: aws/deployment/before_install/remove_old_code.sh
      timeout: 10
      runas: ec2-user
  AfterInstall:
    - location: aws/deployment/after_install/0_create_tmp_dirs.sh 
      timeout: 20
      runas: ec2-user
    - location: aws/deployment/after_install/1_update_figaro.sh
      timeout: 20
      runas: ec2-user
    - location: aws/deployment/after_install/2_install_gems.sh
      timeout: 300
      runas: ec2-user
    - location: aws/deployment/after_install/5_npm_install.sh
      timeout: 300
      runas: ec2-user
    - location: aws/deployment/after_install/3_run_migrations.sh
      runas: ec2-user
    - location: aws/deployment/after_install/4_compile_assets.sh
      runas: ec2-user
      timeout: 60
  ApplicationStart:
    - location: aws/deployment/application_start/start_puma.sh
      timeout: 20
      runas: ec2-user
